apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-secret-store
spec:
  provider:
    vault:
      server: "http://127.0.0.1:8200"
      path: "secret/data"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "my-app-k8s-role"
